version: "3.9"

services:
  react:
    container_name: reactClient
    build:
      context: ./ClientApp
      dockerfile: Dockerfile
    tty: true
    ports:
      - "3000:3000"
    restart: always

  express:
    container_name: expressServer
    build:
      context: ./Server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:8080"

  mongo:
    container_name: mongodb
    image: mongo
    ports: 
        - 27017:27017
    environment:
      MONGO_INITDB_ROOT_ADMINUSERNAME: root
      MONGO_INITDB_ROOT_ADMINPASSWORD: example
    volumes: 
      - ./mongodb:/data/db
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on: 
      - mongodb