version: "3.9"

services:
  react:
    container_name: reactClient
    build:
      context: ./ClientApp
      dockerfile: Dockerfile
    tty: true
    ports:
      - "3000:3000"
    restart: always

  express:
    container_name: expressServer
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    restart: always

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports: 
        - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes: 
      - ./mongodb:/data/db
    restart: always

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongodb"
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on: 
      - mongodb
    restart: always